// Mocks generated by Mockito 5.3.2 from annotations
// in unofficial_open_api/test/unofficial_chat_gpt_open_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chopper/chopper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:unofficial_open_api/model/lib.dart' as _i5;
import 'package:unofficial_open_api/network/service/open_ai_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChopperClient_0 extends _i1.SmartFake implements _i2.ChopperClient {
  _FakeChopperClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeType_1 extends _i1.SmartFake implements Type {
  _FakeType_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2<BodyType> extends _i1.SmartFake
    implements _i2.Response<BodyType> {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OpenAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIService extends _i1.Mock implements _i3.OpenAIService {
  MockOpenAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChopperClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeChopperClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.ChopperClient);
  @override
  set client(_i2.ChopperClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Type get definitionType => (super.noSuchMethod(
        Invocation.getter(#definitionType),
        returnValue: _FakeType_1(
          this,
          Invocation.getter(#definitionType),
        ),
      ) as Type);
  @override
  _i4.Future<_i2.Response<_i5.Data<_i5.Model>>> getModels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Data<_i5.Model>>>.value(
            _FakeResponse_2<_i5.Data<_i5.Model>>(
          this,
          Invocation.method(
            #getModels,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Data<_i5.Model>>>);
  @override
  _i4.Future<_i2.Response<_i5.Model>> getModel({required String? modelId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModel,
          [],
          {#modelId: modelId},
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Model>>.value(
            _FakeResponse_2<_i5.Model>(
          this,
          Invocation.method(
            #getModel,
            [],
            {#modelId: modelId},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Model>>);
  @override
  _i4.Future<_i2.Response<_i5.Completion>> createCompletion(
          _i5.CompletionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCompletion,
          [request],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Completion>>.value(
            _FakeResponse_2<_i5.Completion>(
          this,
          Invocation.method(
            #createCompletion,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Completion>>);
  @override
  _i4.Future<_i2.Response<_i5.Edit>> createEdit(_i5.EditRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEdit,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Response<_i5.Edit>>.value(_FakeResponse_2<_i5.Edit>(
          this,
          Invocation.method(
            #createEdit,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Edit>>);
  @override
  _i4.Future<_i2.Response<_i5.Embedding>> createEmbeddings(
          _i5.EmbeddingRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEmbeddings,
          [request],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Embedding>>.value(
            _FakeResponse_2<_i5.Embedding>(
          this,
          Invocation.method(
            #createEmbeddings,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Embedding>>);
  @override
  _i4.Future<_i2.Response<_i5.Data<_i5.File>>> getFiles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFiles,
          [],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Data<_i5.File>>>.value(
            _FakeResponse_2<_i5.Data<_i5.File>>(
          this,
          Invocation.method(
            #getFiles,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Data<_i5.File>>>);
  @override
  _i4.Future<_i2.Response<_i5.File>> uploadFile(
    String? purpose,
    List<int>? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            purpose,
            file,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Response<_i5.File>>.value(_FakeResponse_2<_i5.File>(
          this,
          Invocation.method(
            #uploadFile,
            [
              purpose,
              file,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.File>>);
  @override
  _i4.Future<_i2.Response<_i5.DeleteResult>> deleteFile(
          {required String? fileId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [],
          {#fileId: fileId},
        ),
        returnValue: _i4.Future<_i2.Response<_i5.DeleteResult>>.value(
            _FakeResponse_2<_i5.DeleteResult>(
          this,
          Invocation.method(
            #deleteFile,
            [],
            {#fileId: fileId},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.DeleteResult>>);
  @override
  _i4.Future<_i2.Response<_i5.File>> getFile({required String? fileId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFile,
          [],
          {#fileId: fileId},
        ),
        returnValue:
            _i4.Future<_i2.Response<_i5.File>>.value(_FakeResponse_2<_i5.File>(
          this,
          Invocation.method(
            #getFile,
            [],
            {#fileId: fileId},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.File>>);
  @override
  _i4.Future<_i2.Response<_i5.FineTune>> createFineTune(
          _i5.FineTuneRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFineTune,
          [request],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.FineTune>>.value(
            _FakeResponse_2<_i5.FineTune>(
          this,
          Invocation.method(
            #createFineTune,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.FineTune>>);
  @override
  _i4.Future<_i2.Response<_i5.Data<_i5.FineTune>>> getFineTunes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFineTunes,
          [],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Data<_i5.FineTune>>>.value(
            _FakeResponse_2<_i5.Data<_i5.FineTune>>(
          this,
          Invocation.method(
            #getFineTunes,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Data<_i5.FineTune>>>);
  @override
  _i4.Future<_i2.Response<_i5.FineTune>> getFineTune(
          {required String? fineTuneId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFineTune,
          [],
          {#fineTuneId: fineTuneId},
        ),
        returnValue: _i4.Future<_i2.Response<_i5.FineTune>>.value(
            _FakeResponse_2<_i5.FineTune>(
          this,
          Invocation.method(
            #getFineTune,
            [],
            {#fineTuneId: fineTuneId},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.FineTune>>);
  @override
  _i4.Future<_i2.Response<_i5.FineTune>> cancelFineTune(
          {required String? fineTuneId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelFineTune,
          [],
          {#fineTuneId: fineTuneId},
        ),
        returnValue: _i4.Future<_i2.Response<_i5.FineTune>>.value(
            _FakeResponse_2<_i5.FineTune>(
          this,
          Invocation.method(
            #cancelFineTune,
            [],
            {#fineTuneId: fineTuneId},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.FineTune>>);
  @override
  _i4.Future<_i2.Response<_i5.Data<_i5.FineTuneEvent>>> getFineTuneEvents(
          {required String? fineTuneId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFineTuneEvents,
          [],
          {#fineTuneId: fineTuneId},
        ),
        returnValue:
            _i4.Future<_i2.Response<_i5.Data<_i5.FineTuneEvent>>>.value(
                _FakeResponse_2<_i5.Data<_i5.FineTuneEvent>>(
          this,
          Invocation.method(
            #getFineTuneEvents,
            [],
            {#fineTuneId: fineTuneId},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Data<_i5.FineTuneEvent>>>);
  @override
  _i4.Future<_i2.Response<_i5.DeleteResult>> deleteFineTune(
          {required String? fineTuneId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFineTune,
          [],
          {#fineTuneId: fineTuneId},
        ),
        returnValue: _i4.Future<_i2.Response<_i5.DeleteResult>>.value(
            _FakeResponse_2<_i5.DeleteResult>(
          this,
          Invocation.method(
            #deleteFineTune,
            [],
            {#fineTuneId: fineTuneId},
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.DeleteResult>>);
  @override
  _i4.Future<_i2.Response<_i5.Moderation>> createModeration(
          _i5.ModerationRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModeration,
          [request],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Moderation>>.value(
            _FakeResponse_2<_i5.Moderation>(
          this,
          Invocation.method(
            #createModeration,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Moderation>>);
  @override
  _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>> createImage(
          _i5.ImageRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createImage,
          [request],
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>>.value(
            _FakeResponse_2<_i5.Data<_i5.ImageUrl>>(
          this,
          Invocation.method(
            #createImage,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>>);
  @override
  _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>> createImageEdit(
    List<int>? image, {
    required String? prompt,
    List<int>? mask,
    int? n = 1,
    String? size,
    String? responseFormat,
    String? user,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createImageEdit,
          [image],
          {
            #prompt: prompt,
            #mask: mask,
            #n: n,
            #size: size,
            #responseFormat: responseFormat,
            #user: user,
          },
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>>.value(
            _FakeResponse_2<_i5.Data<_i5.ImageUrl>>(
          this,
          Invocation.method(
            #createImageEdit,
            [image],
            {
              #prompt: prompt,
              #mask: mask,
              #n: n,
              #size: size,
              #responseFormat: responseFormat,
              #user: user,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>>);
  @override
  _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>> createImageVariation(
    List<int>? image, {
    int? n = 1,
    String? size,
    String? responseFormat,
    String? user,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createImageVariation,
          [image],
          {
            #n: n,
            #size: size,
            #responseFormat: responseFormat,
            #user: user,
          },
        ),
        returnValue: _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>>.value(
            _FakeResponse_2<_i5.Data<_i5.ImageUrl>>(
          this,
          Invocation.method(
            #createImageVariation,
            [image],
            {
              #n: n,
              #size: size,
              #responseFormat: responseFormat,
              #user: user,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.Data<_i5.ImageUrl>>>);
}
